#!/bin/bash

date "+%Y-%m-%d" > current.date

fileprefix="haskell-ohjelmointikieli" 

cat 01-standardikirjasto.md 02-listat.md 03-funktiomaarittely.md 04-funktiorakenteita.md 05-tyypit.md 06-tyyppiluokat.md 07-kuviot.md 08-teksti.md musket-table.md 81-kuun-muodot.md 82-perspektiivi.md 30-gtk.md 31-cairo.md 51-prelude.md > $fileprefix.md

# pandoc $fileprefix.md --from markdown_github+tex_math_dollars+latex_macros --latex-engine=xelatex --no-highlight --number-sections --template=my.latex -V geometry:margin=2.0cm -V fontsize=12pt -o $fileprefix.pdf



pandoc $fileprefix.md $fileprefix.yaml \
  --template=preamble.sty \
  -f markdown+implicit_figures+link_attributes+latex_macros+tex_math_dollars+yaml_metadata_block+grid_tables  \
  --quiet \
  --number-sections \
  --no-highlight \
  --top-level-division=chapter \
  -V date="`date "+%-d.%-m.%Y"`" \
  --pdf-engine=xelatex \
  -o $fileprefix.pdf

if [ $? -eq 0 ]; then
    echo "PDF valmis."
else
    echo ERROR
fi


# Just use

# :!chmod +x %


# --latex-engine=xelatex \
# --toc \
# --highlight-style tango \
# --number-sections \
# --no-highlight \
#  -V date="`date "+%Y-%m-%d"`" \
# --template=my.latex
# -V geometry:margin=2.0cm
# --from markdown_github
# -V fontsize=12pt 
# --no-tex-ligatures
