#!/bin/bash

git add -A
git commit -am "`/home/jhii/sorsat/git/binary/bmt-now`" 
git push

# git status && git add . &&  git commit -m "`/home/jhii/sorsat/git/binary/bmt-now`" && git push origin +HEAD

