#!/bin/bash

# exit when any command fails
set -e

clear

# date "+%Y-%m-%d" > current.date
# date "+%-d.%-m.%Y" > current.date

runhaskell "$1".hs > latest.tikz

pandoc minimal.md metadata.yaml\
  --template=minimal.sty \
  -f markdown+implicit_figures+link_attributes+latex_macros+tex_math_dollars+yaml_metadata_block+grid_tables  \
  -V date="`date "+%-d.%-m.%Y"`" \
  --quiet \
  --pdf-engine=xelatex \
  -o "$1".pdf

cp "$1".pdf ../figs/


if [ $? -eq 0 ]; then
    echo "PDF valmis."
else
    echo ERROR
fi


# Just use

# :!chmod +w %

