#!/bin/bash
# date "+%-d.%-m.%Y" > current.date

date "+%Y-%m-%d" > current.date

pandoc "$1".md chapter.fi.yaml \
  --template=preamble.sty \
  -f markdown+implicit_figures+link_attributes+latex_macros+tex_math_dollars+yaml_metadata_block+grid_tables \
  -V date="`date "+%Y-%m-%d"`" \
  --no-highlight \
  --quiet \
  --number-sections \
  --top-level-division=chapter \
  --pdf-engine=xelatex \
  -o "$1".pdf

if [ $? -eq 0 ]; then
    echo "PDF valmis."
else
    echo ERROR
fi


# Just use

# :!chmod +x %

